os: linux
services: docker
language: node_js
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install wine -qq
node_js: stable
    - $HOME/.cache/electron-builder
script:
    - yarn --link-duplicates
    - node ./knit
    - yarn build -w NSIS --pd './knitting/SKIOApp-win32-x64/'
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file: '.dist/SKIOApp Setup 1.0.0.exe'
  on:
    repo: etaletai13/SKIOApp
    branch: windows
