os: linux
dist: trusty
sudo: required
services: docker
language: node_js
node_js: stable
before_install:
  - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
script:
  - docker run --rm -ti --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS_TAG|TRAVIS|TRAVIS_REPO_|TRAVIS_BUILD_|TRAVIS_BRANCH|TRAVIS_PULL_REQUEST_|APPVEYOR_|CSC_|GH_|GITHUB_|BT_|AWS_|STRIP|BUILD_') --env ELECTRON_CACHE="/root/.cache/electron" --env ELECTRON_BUILDER_CACHE="/root/.cache/electron-builder" -v ${PWD}:/project -v ${PWD##*/}-node-modules:/project/node_modules -v ~/.cache/electron:/root/.cache/electron -v ~/.cache/electron-builder:/root/.cache/electron-builder electronuserland/builder:wine /bin/bash -c " yarn --link-duplicates && node ./knit && yarn build -w nsis --pd \"./knitting/SKIOApp-win32-x86/\""
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file: './dist/SKIOApp Setup 1.0.0.exe'
  on:
    repo: etaletai13/SKIOApp
    branch: windows_x86
