os: osx
osx_image: xcode9.4
language: node_js
node_js: stable
script:
  - yarn --link-duplicates --pure-lockfile
  - node ./build/darwin
  - yarn build -m dmg --pd ./knitting/SKIOApp-darwin-x64/SKIOApp.app/
branches: darwin
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  skip_cleanup: true
  file: dist/SKIOApp-1.0.0.dmg
  on:
    repo: etaletai13/SKIOApp
    branch: darwin
