os: linux
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
    - yarn --link-duplicates
    - node ./build/linux
    - yarn build -l deb rpm --pd '/knitting/knitting/skio-app-linux-x64/'
deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  file: 
    - './dist/SKIOApp_1.0.0_amd64.deb'
    - './dist/SKIOApp_1.0.0_amd64.rpm'
  on:
    repo: etaletai13/SKIOApp
    branch: linux
